runtime: python313
env: standard
instance_class: F4  

automatic_scaling:
  max_instances: 3  

entrypoint: gunicorn -b :$PORT main:server --workers 1 --threads 1 --timeout 120

env_variables:
  PROJECT_ID: "PROJECT_ID_PLACEHOLDER"
  BIGQUERY_DATASET: "DATASET_PLACEHOLDER"
  GCS_BUCKET_NAME: "BUCKET_PLACEHOLDER"

inbound_services:
- warmup